# Generated by Django 3.0.3 on 2022-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220301_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://www.datocms-assets.com/45470/1631795624-logo-django.png', verbose_name='Produit image, url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
